name: Android/Linux Release
on:
  push:
#    branches: [ main]
    tags:
      - '*android'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
#          flutter-version: '3.7.7'
      - run: flutter pub get
      - run:  flutter gen-l10n
      #      - run: flutter test

      - name: Decode android/release.keystore
        run: echo "${{ secrets.KEY_STORE_RELEASE}}" | base64 --decode > android/release.keystore

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties
      - run: flutter build apk  --release
      - run: flutter build appbundle  --release
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

#      - run: flutter config --enable-linux-desktop
#      - run: flutter build linux
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/app/outputs/bundle/release/*.aab"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}
          bodyFile: "assets/RELEASELOG.md"
#      - uses: actions/checkout@v2
#      - uses: ncipollo/release-action@v1