name: Releases

on:
  push:
    tags:
      - 'main'

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12 ]
    permissions:
      contents: write
    steps:
      - Configure Flutter build environment
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
      #      - run: flutter test
      - name: Build Android/Linux App
        if: ${{ matrix.os == 'ubuntu-latest' }}
          - run: |
           flutter pub get
           flutter build apk
           sudo apt-get update -y
           sudo apt-get install -y ninja-build libgtk-3-dev
          - run: flutter config --enable-linux-desktop
          - run: flutter build linux
        # - run: flutter build appbundle
      - name: Build iOS app
        if: ${{ matrix.os == 'macos-12' }}
            - run: flutter pub get
  #            flutter build ipa --release
            - run: flutter build macos --release
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk", "build/ios/iphoneos/Runner.app", " build/macos/Build/Products/Release/chitchat.app"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}
          bodyFile: "assets/CHANGELOG.md"

jobs2:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
