name: 'Mac Release'
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/chitchat.app"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}
          bodyFile: "assets/CHANGELOG.md"
#      - uses: actions/checkout@v2
#      - uses: ncipollo/release-action@v1