name: 'Mac Release'
on:
  push:
    tags:
      - '*mac'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run:  flutter gen-l10n
      - run: flutter build macos --release
      - name: Create the DMG file
        run: |
          hdiutil create -format UDZO -srcfolder build/macos/Build/Products/Release/chitchat.app build/macos/Build/Products/Release/chitchat.dmg
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/chitchat.dmg"
          token: ${{ secrets.PERSONAL_RELEASE_TOKEN }}
          bodyFile: "assets/RELEASELOG.md"
#      - uses: actions/checkout@v2
#      - uses: ncipollo/release-action@v1