name: Flutter Android CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
      - run: flutter pub get
#      - run: flutter test
#      - run: flutter build apk
      - name: Decode android/release.keystore
        run: echo "${{ secrets.KEY_STORE_RELEASE}}" | base64 --decode > android/release.keystore

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES_PROD }}" | base64 --decode > android/key.properties
      - run: flutter build appbundle
